USE ROLE ACCOUNTADMIN;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Database
CREATE DATABASE IF NOT EXISTS HR_JOBS;

-- Change ownership to SYSADMIN
GRANT OWNERSHIP ON DATABASE HR_JOBS TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- Schemas
USE ROLE SYSADMIN;
CREATE SCHEMA IF NOT EXISTS HR_JOBS.STAGING;
CREATE SCHEMA IF NOT EXISTS HR_JOBS.DWH;
CREATE SCHEMA IF NOT EXISTS HR_JOBS.MART;