USE ROLE SECURITYADMIN;

-- Project Admin Role
CREATE ROLE IF NOT EXISTS ROLE_PROJECT_ADMIN;

-- Other functional roles
CREATE ROLE IF NOT EXISTS ROLE_DLT;
CREATE ROLE IF NOT EXISTS ROLE_DBT;
CREATE ROLE IF NOT EXISTS ROLE_STREAMLIT;