USE ROLE SYSADMIN;

-- Grants for DLT role
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_DLT;
GRANT USAGE ON DATABASE HR_JOBS TO ROLE ROLE_DLT;
GRANT USAGE ON SCHEMA HR_JOBS.STAGING TO ROLE ROLE_DLT;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA HR_JOBS.STAGING TO ROLE ROLE_DLT;

-- Grants for DBT role
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_DBT;
GRANT USAGE ON DATABASE HR_JOBS TO ROLE ROLE_DBT;
GRANT USAGE ON SCHEMA HR_JOBS.DWH TO ROLE ROLE_DBT;
GRANT USAGE ON SCHEMA HR_JOBS.MART TO ROLE ROLE_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA HR_JOBS.DWH TO ROLE ROLE_DBT;
GRANT CREATE VIEW ON SCHEMA HR_JOBS.MART TO ROLE ROLE_DBT;

-- Grants for STREAMLIT role
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_STREAMLIT;
GRANT USAGE ON DATABASE HR_JOBS TO ROLE ROLE_STREAMLIT;
GRANT USAGE ON SCHEMA HR_JOBS.MART TO ROLE ROLE_STREAMLIT;
GRANT SELECT ON ALL TABLES IN SCHEMA HR_JOBS.MART TO ROLE ROLE_STREAMLIT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HR_JOBS.MART TO ROLE ROLE_STREAMLIT;

-- Grants for PROJECT_ADMIN role
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_PROJECT_ADMIN;
GRANT USAGE ON DATABASE HR_JOBS TO ROLE ROLE_PROJECT_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HR_JOBS TO ROLE ROLE_PROJECT_ADMIN;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HR_JOBS TO ROLE ROLE_PROJECT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HR_JOBS.STAGING TO ROLE ROLE_PROJECT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HR_JOBS.DWH TO ROLE ROLE_PROJECT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HR_JOBS.MART TO ROLE ROLE_PROJECT_ADMIN;