USE ROLE SECURITYADMIN;

-- Human users
CREATE USER IF NOT EXISTS Maryam
    PASSWORD = '' MUST_CHANGE_PASSWORD = TRUE
    DEFAULT_ROLE = ROLE_PROJECT_ADMIN
    DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS Kanilla
    PASSWORD = '' MUST_CHANGE_PASSWORD = TRUE
    DEFAULT_ROLE = ROLE_PROJECT_ADMIN
    DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS Robin
    PASSWORD = '' MUST_CHANGE_PASSWORD = TRUE
    DEFAULT_ROLE = ROLE_PROJECT_ADMIN
    DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS Andres
    PASSWORD = '' MUST_CHANGE_PASSWORD = TRUE
    DEFAULT_ROLE = ROLE_PROJECT_ADMIN
    DEFAULT_WAREHOUSE = COMPUTE_WH;

-- Role grants
GRANT ROLE ROLE_PROJECT_ADMIN TO USER Maryam;
GRANT ROLE ROLE_PROJECT_ADMIN TO USER Kanilla;
GRANT ROLE ROLE_PROJECT_ADMIN TO USER Robin;
GRANT ROLE ROLE_PROJECT_ADMIN TO USER Andres;