USE ROLE SECURITYADMIN;

-- Service accounts
CREATE USER IF NOT EXISTS SVC_DLT
    PASSWORD = '' MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = ROLE_DLT
    DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS SVC_DBT
    PASSWORD = '' MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = ROLE_DBT
    DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS SVC_STREAMLIT
    PASSWORD = '' MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = ROLE_STREAMLIT
    DEFAULT_WAREHOUSE = COMPUTE_WH;

-- Role grants
GRANT ROLE ROLE_DLT       TO USER SVC_DLT;
GRANT ROLE ROLE_DBT       TO USER SVC_DBT;
GRANT ROLE ROLE_STREAMLIT TO USER SVC_STREAMLIT;