
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS HR_JOBS;

-- Change ownership to SYSADMIN
GRANT OWNERSHIP ON DATABASE HR_JOBS TO ROLE SYSADMIN COPY CURRENT GRANTS;


USE ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS HR_JOBS.STAGING;
CREATE SCHEMA IF NOT EXISTS HR_JOBS.DWH;
CREATE SCHEMA IF NOT EXISTS HR_JOBS.MART;

-------------------------------------------
-- 1) (Roles)
-------------------------------------------
USE ROLE SECURITYADMIN;

-- Team Admin Role
CREATE ROLE IF NOT EXISTS ROLE_PROJECT_ADMIN;


CREATE ROLE IF NOT EXISTS ROLE_DLT;         -- 
CREATE ROLE IF NOT EXISTS ROLE_DBT;         -- 
CREATE ROLE IF NOT EXISTS ROLE_STREAMLIT;   -- JUst SELECT on MART



-------------------------------------------
-- 2) Grant Privileges to Roles
-------------------------------------------
USE ROLE SYSADMIN;

-- DLT:  just STAGING
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_DLT;
GRANT USAGE ON DATABASE HR_JOBS      TO ROLE ROLE_DLT;
GRANT USAGE ON SCHEMA HR_JOBS.STAGING TO ROLE ROLE_DLT;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA HR_JOBS.STAGING TO ROLE ROLE_DLT;

-- DBT: DWH (tabels and view)+ MART (just view )
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_DBT;
GRANT USAGE ON DATABASE HR_JOBS      TO ROLE ROLE_DBT;
GRANT USAGE ON SCHEMA HR_JOBS.DWH    TO ROLE ROLE_DBT;
GRANT USAGE ON SCHEMA HR_JOBS.MART   TO ROLE ROLE_DBT;
GRANT CREATE TABLE, CREATE VIEW      ON SCHEMA HR_JOBS.DWH  TO ROLE ROLE_DBT;
GRANT CREATE VIEW                    ON SCHEMA HR_JOBS.MART TO ROLE ROLE_DBT;

-- STREAMLIT:Select on Mart now and future tables
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_STREAMLIT;
GRANT USAGE ON DATABASE HR_JOBS      TO ROLE ROLE_STREAMLIT;
GRANT USAGE ON SCHEMA HR_JOBS.MART   TO ROLE ROLE_STREAMLIT;
GRANT SELECT ON ALL TABLES IN SCHEMA HR_JOBS.MART TO ROLE ROLE_STREAMLIT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HR_JOBS.MART TO ROLE ROLE_STREAMLIT;


-- What can an admin do?
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_PROJECT_ADMIN;
GRANT USAGE ON DATABASE HR_JOBS      TO ROLE ROLE_PROJECT_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HR_JOBS TO ROLE ROLE_PROJECT_ADMIN;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HR_JOBS TO ROLE ROLE_PROJECT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HR_JOBS.STAGING TO ROLE ROLE_PROJECT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HR_JOBS.DWH     TO ROLE ROLE_PROJECT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA HR_JOBS.MART    TO ROLE ROLE_PROJECT_ADMIN;

-------------------------------------------
-- 3) User Admin

-------------------------------------------
USE ROLE SECURITYADMIN;


CREATE USER IF NOT EXISTS Maryam
  PASSWORD = '' MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = ROLE_PROJECT_ADMIN
  DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS Kanilla
  PASSWORD = '' MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = ROLE_PROJECT_ADMIN
  DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS Robin
  PASSWORD = '' MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = ROLE_PROJECT_ADMIN
  DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS Andres
  PASSWORD = '' MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = ROLE_PROJECT_ADMIN
  DEFAULT_WAREHOUSE = COMPUTE_WH;


-- GRANT ROLE ROLE_PROJECT_ADMIN TO All users;


GRANT ROLE ROLE_PROJECT_ADMIN TO USER Maryam;
GRANT ROLE ROLE_PROJECT_ADMIN TO USER Kanilla;
GRANT ROLE ROLE_PROJECT_ADMIN TO USER Robin;
GRANT ROLE ROLE_PROJECT_ADMIN TO USER Andres;

-------------------------------------------
-- 4)Machin users
-------------------------------------------
CREATE USER IF NOT EXISTS SVC_DLT
  PASSWORD = '' MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = ROLE_DLT
  DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS SVC_DBT
  PASSWORD = '' MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = ROLE_DBT
  DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE USER IF NOT EXISTS SVC_STREAMLIT
  PASSWORD = '' MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = ROLE_STREAMLIT
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE ROLE_DLT       TO USER SVC_DLT;
GRANT ROLE ROLE_DBT       TO USER SVC_DBT;
GRANT ROLE ROLE_STREAMLIT TO USER SVC_STREAMLIT;

Grant ROLE ROLE_DLT to ROLE ROLE_DBT;
SHOW GRANTS TO ROLE ROLE_DBT;

SHOW SCHEMAS IN DATABASE HR_JOBS;

USE DATABASE HR_JOBS;
CREATE SCHEMA IF NOT EXISTS warehouse;
USE ROLE SYSADMIN;

-- سطح Database
GRANT USAGE ON DATABASE HR_JOBS TO ROLE ROLE_DBT;

-- سطح Schema (DWH و MART طبق طراحی‌ت)
GRANT USAGE ON SCHEMA HR_JOBS.DWH  TO ROLE ROLE_DBT;
GRANT USAGE ON SCHEMA HR_JOBS.MART TO ROLE ROLE_DBT;

-- مجوز ساخت آبجکت‌ها
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA HR_JOBS.DWH  TO ROLE ROLE_DBT;  -- ساخت مدل‌های dbt
GRANT CREATE VIEW                ON SCHEMA HR_JOBS.MART TO ROLE ROLE_DBT; -- فقط View در مارت

GRANT USAGE ON SCHEMA HR_JOBS.WAREHOUSE TO ROLE ROLE_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA HR_JOBS.WAREHOUSE TO ROLE ROLE_DBT;

Grant select on future views in schema HR_JOBS.warehouse to ROLE ROLE_DBT;

