USE ROLE SYSADMIN;

USE DATABASE HR_JOBS;   

CREATE SCHEMA IF NOT EXISTS marts;

SHOW SCHEMAS IN DATABASE HR_JOBS;

USE ROLE securityadmin;

GRANT USAGE,
CREATE TABLE,
CREATE VIEW ON SCHEMA HR_JOBS.marts TO ROLE ROLE_DBT;

-- grant CRUD and select tables and views
GRANT SELECT,
INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA HR_JOBS.marts TO ROLE ROLE_DBT;
GRANT SELECT ON ALL VIEWS IN SCHEMA HR_JOBS.marts TO ROLE ROLE_DBT;

-- grant CRUD and select on future tables and views
GRANT SELECT,
INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA HR_JOBS.marts TO ROLE ROLE_DBT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HR_JOBS.marts TO ROLE ROLE_DBT;

SELECT CURRENT_USER(), CURRENT_ROLE();
USE ROLE SECURITYADMIN;

GRANT ROLE ROLE_DBT TO USER mmoghadasi;

USE ROLE ROLE_DBT;

SHOW GRANTS ON SCHEMA HR_JOBS.marts;

-- manual test
USE SCHEMA HR_JOBS.marts;
CREATE TABLE test (id INTEGER);
SHOW TABLES;
DROP TABLE TEST;